version: '2'

services:

  web:
    image: nginx:1.9
    ports:
      - "8231:80"
    depends_on:
      - php
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/sites-enabled:/etc/nginx/sites-enabled
    volumes_from:
      - php:ro
    command: nginx -c /etc/nginx/nginx.conf

  php:
    image: php:fpm
    volumes:
      - ./app:/var/www/html
